services:
  - docker

script:
  - make release

after_success:
  - docker images
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push thaedal/python3-flask-alpine;
    fi
